# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build all formats
formats: 
  - htmlzip

# Specify Python requirements
python:
  install:
    - requirements: docs/requirements.txt
