[project]
requires-python = ">=3.7"

[build-system]
requires = ["setuptools>=42", 
            "wheel", 
            "cmaketools>=0.1.6", 
            "numpy>=1.15",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ['py36','py37','py38']
