name: Continuous Integration

on:
  push:
    paths: src/tfc/* tests/*

jobs:
  lint and test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: lint
        uses: psf/black@stable
        with:
          args: "./src/tfc --check"

      - run: "sudo apt-get update && sudo apt-get install -y swig gcc g++"
      - run: python -m pip install wheel setuptools numpy pytest
      - run: python setup.py bdist_wheel
      - run: pip install ./dist/*.whl

      - name: python tests
        run: pytest tests
