name: Run most examples

on:
  workflow_dispatch:

jobs:
  run_examples:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - run: "sudo apt-get update && sudo apt-get install -y swig gcc g++ graphviz"
      - run: python -m pip install wheel setuptools numpy pytest
      - run: python setup.py bdist_wheel
      - run: pip install ./dist/*.whl
      - run: pip install -r ./requirements.txt

      - name: run all examples
        run: "cd tests; ./test_all -j 5"
